import assert from 'node:assert/strict';
import {compareOverview,parsePackingRows,normalizeCode} from '../site/local-engine.js';
const rows=[{row:1,name:'Box',sku:'BOX-12',expected:1,source_text:'Box BOX-12 1'},{row:2,name:'Towel',sku:'TWL-23',expected:1,source_text:'Towel TWL-23 1'}];
const label=(sku,x=.1,confidence=95)=>({sku,bbox:[x,.1,.12,.05],confidence});
let r=compareOverview(rows,[label('BOX-12'),label('TWL-23',.4)]);assert.deepEqual(r.map(x=>x.status),['confirmed','confirmed']);
r=compareOverview(rows,[label('BOX-12'),label('BOX-12',.5)]);assert.equal(r[0].status,'mismatch');assert.equal(r[0].observed,2);
r=compareOverview(rows,[label('BOX-12'),label('BOX-12',.105)]);assert.equal(r[0].observed,1);assert.equal(r[0].status,'confirmed');
r=compareOverview(rows,[label('TWL-99')]);assert.equal(r[1].status,'mismatch');assert.match(r[1].explanation,/does not prove/);
r=compareOverview(rows,[]);assert.ok(r.every(x=>x.status==='unverified'&&x.observed===null));assert.ok(r.every(x=>x.evidence.length===1));
r=compareOverview(rows,[label('BOX-12',.1,65)]);assert.equal(r[0].status,'unverified');
r=compareOverview(rows,[label('BOX-1Z')]);assert.equal(r[0].status,'unverified');
r=compareOverview([{...rows[0],source_confidence:60}],[label('BOX-12')]);assert.equal(r[0].status,'unverified');
r=compareOverview([{...rows[0],expected:3}],[label('BOX-12')]);assert.equal(r[0].status,'unverified');assert.match(r[0].explanation,/not proof/);
const items=[['1',10],['Small towel',40],['TWL-23',180],['1',240]].map(([str,x])=>({str,transform:[12,0,0,12,x,600],width:str.length*6}));r=parsePackingRows(items,300,800);assert.equal(r[0].sku,'TWL-23');assert.ok(r[0].source_bbox[1]>0);assert.throws(()=>parsePackingRows([],300,800));assert.notEqual(normalizeCode('BOX_12'),normalizeCode('BOX-12'));
console.log('PASS: automatic visible matches, extra labels, overlap deduplication, wrong code, unreadable/absent labels, OCR ambiguity, document confidence, conservative quantities and source row coordinates.');
